export const FETCHING_MOVIES_REQUEST = 'FETCHING_MOVIES_REQUEST';
export const FETCHING_MOVIES_SUCCESS = 'FETCHING_MOVIES_SUCCESS';
export const FETCHING_MOVIES_FALIURE = 'FETCHING_MOVIES_FALIURE';
export const FETCHING_FILTER_MOVIES = 'FETCHING_FILTER_MOVIES';


export const FETCHING_MOVIES_DETAILS_SUCCESS = 'FETCHING_MOVIES_DETAILS_SUCCESS';
export const FETCHING_MOVIES_DETAILS_REQUEST = 'FETCHING_MOVIES_DETAILS_REQUEST';
export const FETCHING_MOVIES_DETAILS_FALIURE = 'FETCHING_MOVIES_DETAILS_FALIURE';

